Algoritmo "ordenacao"
// 
// Autor(a)    : Marcus Passos
// Data atual  : 7/10/2022
Var

  x,y : inteiro

Inicio

  escreval("Digite dois números: ")
  leia(x)
  leia(y)
  
  enquanto x <> y faca
    se (x > y) entao
      escreval("Decrescente!")
    senao
      escreval("Crescente!")
    fimse
    escreval("Digite outros dois números: ")
    leia(x)
    leia(y)
  fimenquanto
    
  
  
  
  escreva()

Fimalgoritmo